class MultipleCatch
{
 public static void main(String[] args)
 {
   try
   {
    int[] arr={1,2,3,5};
    System.out.println(arr[7]/0);
  }
  catch(ArithmeticException e)
  {
   System.out.println("Error:Arithmetic Exception found"+e.getMessage());
  }
  catch(ArrayIndexOutOfBoundsException e)
  {
    System.out.println("Error:ArrayIndexOutOfBoundsException"+e.getMessage());
  }
 catch(NumberFormatException e)
 {
   System.out.println("Error:NumberFormatException found"+e.getMessage());
  }
System.out.println("Multiple catch program is executed");
 }
}







